"""update

Revision ID: 3b507332d542
Revises: 45822bd1ded1
Create Date: 2025-05-18 18:05:25.891328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b507332d542'
down_revision: Union[str, None] = '45822bd1ded1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('department', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'classes', 'department', ['department'], ['id'])
    op.add_column('staffs', sa.Column('department', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'staffs', 'department', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.drop_column('staffs', 'department')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'department')
    # ### end Alembic commands ###
