"""database UPdate

Revision ID: 45822bd1ded1
Revises: 26ceda8c92eb
Create Date: 2025-05-18 17:31:09.278121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45822bd1ded1'
down_revision: Union[str, None] = '26ceda8c92eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_department_fkey', 'classes', type_='foreignkey')
    op.drop_column('classes', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('department', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('classes_department_fkey', 'classes', 'department', ['department'], ['id'])
    # ### end Alembic commands ###
